/*
 * RJobDetails.cs
 *
 * Copyright (C) 2010-2015 by Microsoft Corporation
 *
 * This program is licensed to you under the terms of Version 2.0 of the
 * Apache License. This program is distributed WITHOUT
 * ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
 * Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0) for more details.
 *
 */

using System;

namespace DeployR
{
/// <summary>
/// Details of a Job
/// </summary>
/// <remarks></remarks>
    public class RJobDetails
    {

        private String m_descr = "";
        private String m_id = "";
        private String m_name = "";
        private int m_onrepeat = 0;
        private String m_project = "";
        private long m_schedinterval = 0;
        private int m_schedrepeat = 0;
        private long m_schedstart = 0;
        private String m_status = "";
        private String m_statusMsg = "";
        private long m_timeStart = 0;
        private long m_timeCode = 0;
        private long m_timeTotal = 0;
        private String m_tag = "";

        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <remarks></remarks>
        protected RJobDetails()
        {

        }

        internal RJobDetails(String descr, String id, String name, int onrepeat, String project, long schedinterval, int schedrepeat, long schedstart, String status, String statusMsg, long timeStart, long timeCode, long timeTotal, String tag)
        {

            m_descr = descr;
            m_id = id;
            m_name = name;
            m_onrepeat = onrepeat;
            m_project = project;
            m_schedinterval = schedinterval;
            m_schedrepeat = schedrepeat;
            m_schedstart = schedstart;
            m_status = status;
            m_statusMsg = statusMsg;
            m_timeStart = timeStart;
            m_timeCode = timeCode;
            m_timeTotal = timeTotal;
            m_tag = tag;

        }

        /// <summary>
        /// Job description
        /// </summary>
        /// <value>description</value>
        /// <returns>description</returns>
        /// <remarks></remarks>
        public String descr
        {
            get
            {
                return m_descr;
            }
            set
            {
                m_descr = value;
            }
        }

        /// <summary>
        /// Job id
        /// </summary>
        /// <returns>id</returns>
        /// <remarks></remarks>
        public String id
        {
            get
            {
                return m_id;
            }
        }

        /// <summary>
        /// Job name
        /// </summary>
        /// <value>name</value>
        /// <returns>nameg</returns>
        /// <remarks></remarks>
        public String name
        {
            get
            {
                return m_name;
            }
            set
            {
                m_name = value;
            }
        }

        /// <summary>
        /// On repeat of the job
        /// </summary>
        /// <returns>on repeat value</returns>
        /// <remarks></remarks>
        public int onrepeat
        {
            get
            {
                return m_onrepeat;
            }
        }

        /// <summary>
        /// Name of project generated by job
        /// </summary>
        /// <returns>project name</returns>
        /// <remarks></remarks>
        public String project
        {
            get
            {
                return m_project;
            }
        }

        /// <summary>
        ///  Job scheduled repeat interval
        /// </summary>
        /// <returns>repeat intervale</returns>
        /// <remarks></remarks>
        public long schedinterval
        {
            get
            {
                return m_schedinterval;
            }
        }

        /// <summary>
        ///  Job scheduled repeat count
        /// </summary>
        /// <returns>repeat count</returns>
        /// <remarks></remarks>
        public int schedrepeat
        {
            get
            {
                return m_schedrepeat;
            }
        }

        /// <summary>
        ///  Job scheduled start time (UTC).
        /// </summary>
        /// <returns>scheduled start time</returns>
        /// <remarks></remarks>
        public long schedstart
        {
            get
            {
                return m_schedstart;
            }
        }

        /// <summary>
        ///  Job status
        /// </summary>
        /// <returns>status</returns>
        /// <remarks></remarks>
        public RJob.Status status
        {
            get
            {
                return RJob.Status.fromString(m_status);
            }
        }

        /// <summary>
        ///  Job status message
        /// </summary>
        /// <returns>status message</returns>
        /// <remarks></remarks>
        public String statusMsg
        {
            get
            {
                return m_statusMsg;
            }
        }


        /// <summary>
        /// Start time (millis) for job
        /// </summary>
        /// <returns>Long value containing Start time (millis) for job</returns>
        /// <remarks></remarks>
        public long timeStart
        {
            get
            {
                return m_timeStart;
            }
        }

        /// <summary>
        /// Code execution time (millis) for job
        /// </summary>
        /// <returns>Long value containing Code execution time (millis) for job</returns>
        /// <remarks></remarks>
        public long timeCode
        {
            get
            {
                return m_timeCode;
            }
        }

        /// <summary>
        /// Total time (millis) for job
        /// </summary>
        /// <returns>Long value containing Total time (millis) for job</returns>
        /// <remarks></remarks>
        public long timeTotal
        {
            get
            {
                return m_timeTotal;
            }
        }


        /// <summary>
        /// Job execution tag
        /// </summary>
        /// <returns>String value containing the tag for job</returns>
        /// <remarks></remarks>
        public long tag
        {
            get
            {
                long returnValue = 0;
                returnValue = long.Parse(m_tag);
                return returnValue;
            }
        }

    }
}