/*
 * RResponse.cs
 *
 * Copyright (C) 2010-2014 by Revolution Analytics Inc.
 *
 * This program is licensed to you under the terms of Version 2.0 of the
 * Apache License. This program is distributed WITHOUT
 * ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
 * Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0) for more details.
 *
 */

using System;

namespace DeployR
{
/// <summary>
/// RResponse Interface
/// </summary>
/// <remarks></remarks>
    public interface RResponse
    {
        /// <summary>
        /// Error Code generated by calling API
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks></remarks>
        int ErrorCode { get; }
        /// <summary>
        /// Error Message generated by calling API
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks></remarks>
        String ErrorMsg { get; }
        /// <summary>
        /// Indication if calling API succeeded
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks></remarks>
        Boolean Success { get; }

    }
}